[terminal.shell]
program = "bash"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "D"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "U"
mods = "Control"

[terminal]

[colors.bright]
black = "0x6e6a86"
blue = "0x31748f"
cyan = "0xebbcba"
green = "0x9ccfd8"
magenta = "0xc4a7e7"
red = "0xeb6f92"
white = "0xffffff"
yellow = "0xf6c177"

[colors.normal]
black = "0x2a273f"
blue = "0x31748f"
cyan = "0xebbcba"
green = "0x9ccfd8"
magenta = "0xc4a7e7"
red = "0xeb6f92"
white = "0xe0def4"
yellow = "0xf6c177"

[colors.primary]
background = "0x000000"
foreground = "0xe0def4"


[window]
decorations = "none"
opacity = 0.85


[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true


[keyboard]
