#!/usr/bin/env zsh

# Directories to search for virtualenvs


  DIRS_TO_CHECK=(~/projects ~/Tutorial ~/temp)

# Interactive picker
activate_env_glob() {
  selected=$(fd -HI --type f --full-path '/bin/activate$' "${DIRS_TO_CHECK[@]}" --absolute-path | awk -F'/' '{ print $(NF-3),"->",$0 }' |fzf --delimiter=' ' | awk '{ print $3 }')
  if [ -n "$selected" ]; then
    source "$selected"
    echo "Activated: $selected"
  fi
}

get_env() {
  for dir in ".env" ".venv"; do
    if [ -f "$dir/bin/activate" ]; then
      source "$dir/bin/activate"
      echo "Activated $dir"
      return
    fi
  done
  echo "Python env not found in $(pwd)"
}

activate() {
  if [ "$1" = "ls" ]; then
    activate_env_glob
  else
    get_env
  fi
}
activate $1
