#!/usr/bin/env bash

main() {
  path="$1"

  if [[ ! -e "$path" ]]; then
    echo "$path doesn't exist"
    exit 1
  fi

  cat >~/.config/hypr/hyprpaper.conf <<EOF
preload = $path
wallpaper = eDP-1, $path
EOF

  pkill hyprpaper || true
  hyprpaper >/dev/null 2>&1 &
  disown
  switch
}

choice() {
  echo $(
    cd ~/Pictures/WallPaper/
    fzf --preview 'chafa -f kitty --size=80x40 {}' \
      --preview-window=right:70% \
      --height=100% --layout=reverse \
      --header="Choose an image"
  )
}

# call choice, store result in a variable
selected_image=$(choice)

# check if something was selected
if [[ -n "$selected_image" ]]; then
  main "$HOME/Pictures/WallPaper/$selected_image"
else
  echo "No image selected."
  exit 0
fi
