#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$(find ~/projects ~/work ~/Tutorial -mindepth 1 -maxdepth 1 -type d | fzf)
fi

echo "alias th='cd $selected'" >~/bash/volitile

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s $selected_name -n vim -c $selected \; \
    new-window -n cli -c $selected
  exit 0
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
  tmux new-session -s $selected_name -n vim -c $selected \; \
    new-window -n cli -c $selected
fi

tmux switch-client -t $selected_name
